# Generated by Django 5.2 on 2026-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=10)),
                ('in_bytes', models.BigIntegerField(default=0)),
                ('out_bytes', models.BigIntegerField(default=0)),
                ('in_errors', models.IntegerField(default=0)),
                ('out_errors', models.IntegerField(default=0)),
                ('in_mbps', models.FloatField(default=0.0)),
                ('out_mbps', models.FloatField(default=0.0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='devices.interface')),
            ],
            options={
                'verbose_name': 'Interface Stats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['interface', '-timestamp'], name='metrics_int_interfa_7434ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_percent', models.FloatField()),
                ('mem_percent', models.FloatField()),
                ('uptime_secs', models.BigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_stats', to='devices.device')),
            ],
            options={
                'verbose_name': 'System Health',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='metrics_sys_device__598db4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VMStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vm_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('mem_assigned_mb', models.IntegerField(default=0)),
                ('repl_health', models.CharField(blank=True, max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_stats', to='devices.device')),
            ],
            options={
                'verbose_name': 'VM Stats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'vm_name', '-timestamp'], name='metrics_vms_device__87d65f_idx')],
            },
        ),
    ]
