# Generated by Django 5.2 on 2026-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealth',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
