# Generated by Django 5.2 on 2026-05-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_encrypt_credentials'),
        ('metrics', '0002_systemhealth_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Ngày')),
                ('in_mbps_avg', models.FloatField(default=0.0)),
                ('in_mbps_max', models.FloatField(default=0.0)),
                ('out_mbps_avg', models.FloatField(default=0.0)),
                ('out_mbps_max', models.FloatField(default=0.0)),
                ('in_errors', models.IntegerField(default=0)),
                ('out_errors', models.IntegerField(default=0)),
                ('sample_count', models.IntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_daily', to='devices.interface')),
            ],
            options={
                'verbose_name': 'Interface Stats (Daily)',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['interface', '-day'], name='metrics_int_interfa_ff0c51_idx')],
                'unique_together': {('interface', 'day')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceStatsHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(verbose_name='Đầu giờ (truncated)')),
                ('in_mbps_avg', models.FloatField(default=0.0)),
                ('in_mbps_max', models.FloatField(default=0.0)),
                ('out_mbps_avg', models.FloatField(default=0.0)),
                ('out_mbps_max', models.FloatField(default=0.0)),
                ('in_errors', models.IntegerField(default=0, verbose_name='Tổng in errors')),
                ('out_errors', models.IntegerField(default=0, verbose_name='Tổng out errors')),
                ('sample_count', models.IntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_hourly', to='devices.interface')),
            ],
            options={
                'verbose_name': 'Interface Stats (Hourly)',
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['interface', '-hour'], name='metrics_int_interfa_dfaa01_idx')],
                'unique_together': {('interface', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SystemHealthDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Ngày')),
                ('cpu_avg', models.FloatField()),
                ('cpu_max', models.FloatField()),
                ('mem_avg', models.FloatField()),
                ('mem_max', models.FloatField()),
                ('sample_count', models.IntegerField(default=0, verbose_name='Số mẫu hourly')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_daily', to='devices.device')),
            ],
            options={
                'verbose_name': 'System Health (Daily)',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['device', '-day'], name='metrics_sys_device__1e9c84_idx')],
                'unique_together': {('device', 'day')},
            },
        ),
        migrations.CreateModel(
            name='SystemHealthHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(verbose_name='Đầu giờ (truncated)')),
                ('cpu_avg', models.FloatField()),
                ('cpu_max', models.FloatField()),
                ('mem_avg', models.FloatField()),
                ('mem_max', models.FloatField()),
                ('sample_count', models.IntegerField(default=0, verbose_name='Số mẫu raw')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_hourly', to='devices.device')),
            ],
            options={
                'verbose_name': 'System Health (Hourly)',
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['device', '-hour'], name='metrics_sys_device__bdbe69_idx')],
                'unique_together': {('device', 'hour')},
            },
        ),
    ]
