# Generated by Django 5.2 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_aggregation_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmstats',
            name='repl_health',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
