# Generated by Django 5.2 on 2026-07-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_wifi_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealth',
            name='cpu_hv_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_read_iops',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_read_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_write_iops',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_write_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='mem_available_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='net_mbps_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='cpu_hv_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='cpu_hv_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_iops_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_iops_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_latency_ms_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_latency_ms_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_iops_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_iops_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_latency_ms_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_latency_ms_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='mem_available_mb_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='mem_available_mb_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='net_mbps_total_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='net_mbps_total_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='cpu_hv_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='cpu_hv_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_iops_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_iops_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_latency_ms_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_latency_ms_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_iops_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_iops_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_latency_ms_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_latency_ms_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='mem_available_mb_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='mem_available_mb_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='net_mbps_total_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='net_mbps_total_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
