# Generated by Django 5.2 on 2026-07-07 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_topologylink_switch_kind'),
        ('metrics', '0006_systemhealth_cpu_hv_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemhealth',
            name='avg_io_size_kb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_queue_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_read_throughput_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealth',
            name='disk_write_throughput_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='avg_io_size_kb_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='avg_io_size_kb_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_queue_length_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_queue_length_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_throughput_mbps_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_read_throughput_mbps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_throughput_mbps_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthdaily',
            name='disk_write_throughput_mbps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='avg_io_size_kb_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='avg_io_size_kb_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_queue_length_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_queue_length_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_throughput_mbps_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_read_throughput_mbps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_throughput_mbps_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemhealthhourly',
            name='disk_write_throughput_mbps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VolumeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('volume_name', models.CharField(max_length=100)),
                ('read_iops', models.FloatField(blank=True, null=True)),
                ('write_iops', models.FloatField(blank=True, null=True)),
                ('read_mbps', models.FloatField(blank=True, null=True)),
                ('write_mbps', models.FloatField(blank=True, null=True)),
                ('read_latency_ms', models.FloatField(blank=True, null=True)),
                ('write_latency_ms', models.FloatField(blank=True, null=True)),
                ('queue_length', models.FloatField(blank=True, null=True)),
                ('avg_io_size_kb', models.FloatField(blank=True, null=True)),
                ('vm_names', models.JSONField(blank=True, default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_stats', to='devices.device')),
            ],
            options={
                'verbose_name': 'Volume Stats',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'volume_name', '-timestamp'], name='metrics_vol_device__e6c895_idx')],
            },
        ),
    ]
