# Generated by Django 5.2 on 2026-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_systemhealth_avg_io_size_kb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumestats',
            name='current_queue_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumestats',
            name='idle_time_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumestats',
            name='split_io_per_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumestats',
            name='transfers_per_sec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
