# Generated by Django 6.0.6 on 2026-09-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_device_ilo_ip_address_device_ilo_password_and_more'),
        ('metrics', '0008_volumestats_current_queue_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('controller_health_code', models.IntegerField(blank=True, null=True, verbose_name='RAID Controller Health')),
                ('logical_drive_worst_code', models.IntegerField(blank=True, null=True, verbose_name='Logical Drive Health (worst)')),
                ('missing_disk_count', models.IntegerField(blank=True, null=True, verbose_name='Số đĩa mất (404)')),
                ('enclosure_mismatch_count', models.IntegerField(blank=True, null=True, verbose_name='Số enclosure bất thường')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_health', to='devices.device')),
            ],
            options={
                'verbose_name': 'Hardware Health (iLO)',
                'verbose_name_plural': 'Hardware Health (iLO)',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='metrics_har_device__e8a8b4_idx')],
            },
        ),
    ]
