# Generated by Django 5.2.16 on 2026-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_hardwarehealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarehealth',
            name='ams_device_discovery',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Agentless Management Service'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='battery_health_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Smart Storage Battery Health'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='fan_worst_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fan Health (worst)'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='memory_health_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memory Health'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='power_redundancy_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Power Redundancy OK'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='power_supply_worst_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Power Supply Health (worst)'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='processor_health_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Processor Health'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='temperature_worst_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature Health (worst)'),
        ),
    ]
