# Generated by Django 5.2.16 on 2026-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_hardwarehealth_ams_device_discovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarehealth',
            name='bios_hardware_health_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='BIOS/Hardware Health'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='fan_redundancy_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fan Redundancy OK'),
        ),
        migrations.AddField(
            model_name='hardwarehealth',
            name='network_health_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Network Health'),
        ),
    ]
