# Generated by Django 5.2 on 2026-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên rule')),
                ('device_type', models.CharField(default='all', max_length=20, verbose_name='Loại thiết bị')),
                ('metric', models.CharField(max_length=100, verbose_name='Metric')),
                ('condition', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('eq', '='), ('ne', '≠'), ('gte', '≥'), ('lte', '≤')], max_length=5, verbose_name='Điều kiện')),
                ('threshold', models.FloatField(verbose_name='Ngưỡng')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='Mức độ')),
                ('duration_min', models.IntegerField(default=0, verbose_name='Kéo dài (phút)')),
                ('channels', models.JSONField(default=list, verbose_name='Kênh thông báo')),
                ('enabled', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('metric_value', models.FloatField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': 'Alert',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('error', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'ordering': ['-sent_at'],
            },
        ),
    ]
