# Generated by Django 5.2 on 2026-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='device_type',
            field=models.CharField(choices=[('all', 'Tất cả'), ('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('hyperv', 'HyperV Host')], default='all', max_length=20, verbose_name='Loại thiết bị'),
        ),
    ]
