# Generated by Django 5.2 on 2026-06-23 12:50

from django.db import migrations, models


def seed_offline_rule(apps, schema_editor):
    """Tạo sẵn rule 'Thiết bị offline → Telegram' (idempotent)."""
    AlertRule = apps.get_model("alerts", "AlertRule")
    AlertRule.objects.get_or_create(
        name="Thiết bị offline",
        defaults=dict(device_type="all", metric="device_online",
                      condition="eq", threshold=0, severity="CRITICAL",
                      duration_min=0, channels=["telegram"], enabled=True),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alertrule_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_enabled', models.BooleanField(default=True, verbose_name='Bật gửi Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, default='', help_text='Chat/group ID nhận cảnh báo (vd -100123456789). Để trống = dùng giá trị trong .env.', max_length=64, verbose_name='Telegram Chat ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình cảnh báo',
            },
        ),
        migrations.RunPython(seed_offline_rule, migrations.RunPython.noop),
    ]
