# Generated by Django 5.2.16 on 2026-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_seed_wifi_ap_offline_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='kind',
            field=models.CharField(choices=[('fire', 'Fire'), ('recovery', 'Recovery')], default='fire', max_length=10),
        ),
    ]
