# Generated by Django 5.2.16 on 2026-09-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alertnotification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'sent_at'], name='alerts_aler_status_9bc5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='alertnotification',
            index=models.Index(fields=['status', 'updated_at'], name='alerts_aler_status_5555f1_idx'),
        ),
    ]
