# Generated by Django 5.2.16 on 2026-09-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alertnotification_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
