# Generated by Django 5.2 on 2026-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thiết bị')),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('hyperv', 'HyperV Host')], max_length=20, verbose_name='Loại')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Địa chỉ IP')),
                ('vendor', models.CharField(choices=[('cisco', 'Cisco'), ('huawei', 'Huawei'), ('hp', 'HP/Aruba')], max_length=50, verbose_name='Hãng')),
                ('os_family', models.CharField(blank=True, max_length=50, verbose_name='OS Family')),
                ('protocol', models.CharField(choices=[('snmp', 'SNMP'), ('ssh', 'SSH'), ('winrm', 'WinRM')], max_length=10, verbose_name='Giao thức')),
                ('snmp_version', models.CharField(default='v2c', max_length=5)),
                ('snmp_community', models.CharField(blank=True, max_length=200, verbose_name='SNMP Community')),
                ('ssh_username', models.CharField(blank=True, max_length=100, verbose_name='SSH Username')),
                ('ssh_password', models.CharField(blank=True, max_length=200, verbose_name='SSH Password')),
                ('collect_interval', models.IntegerField(default=300, verbose_name='Chu kỳ quét (giây)')),
                ('uplink_ports', models.JSONField(default=list, verbose_name='Uplink/Trunk ports')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('enabled', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Lần poll cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Danh sách thiết bị',
                'ordering': ['device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_index', models.IntegerField(verbose_name='Interface Index')),
                ('name', models.CharField(max_length=100, verbose_name='Tên port')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('is_uplink', models.BooleanField(default=False, verbose_name='Là uplink/trunk')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='devices.device')),
            ],
            options={
                'verbose_name': 'Interface',
                'ordering': ['if_index'],
                'unique_together': {('device', 'if_index')},
            },
        ),
    ]
