# Generated by Django 5.2 on 2026-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('hyperv', 'HyperV Host')], max_length=20, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('huawei', 'Huawei'), ('hp', 'HP/Aruba'), ('mikrotik', 'MikroTik'), ('fortinet', 'Fortinet'), ('microsoft', 'Microsoft')], max_length=50, verbose_name='Hãng'),
        ),
    ]
