# Generated by Django 5.2 on 2026-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type_alter_device_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Địa chỉ IP')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='Hostname')),
                ('snmp_status', models.BooleanField(default=False, verbose_name='Hỗ trợ SNMP')),
                ('sys_descr', models.TextField(blank=True, verbose_name='Mô tả SNMP')),
                ('discovered_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian phát hiện')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Đã import')),
            ],
            options={
                'verbose_name': 'Thiết bị phát hiện',
                'verbose_name_plural': 'Thiết bị phát hiện tự động',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='backup_enabled',
            field=models.BooleanField(default=False, verbose_name='Sao lưu cấu hình'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.CharField(choices=[('snmp', 'SNMP'), ('ssh', 'SSH'), ('winrm', 'WinRM'), ('ping', 'Ping/ICMP')], max_length=10, verbose_name='Giao thức'),
        ),
    ]
