# Generated by Django 5.2 on 2026-05-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_encrypt_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], max_length=20, verbose_name='Trạng thái')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn file')),
                ('file_size_kb', models.FloatField(default=0, verbose_name='Dung lượng (KB)')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi (Nếu có)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chạy')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='devices.device', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Lịch sử sao lưu',
                'verbose_name_plural': 'Lịch sử sao lưu cấu hình',
                'ordering': ['-created_at'],
            },
        ),
    ]
