# Generated by Django 5.2 on 2026-06-20 03:57

import apps.devices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_create_rbac_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='snmpv3_auth_password',
            field=apps.devices.fields.EncryptedCharField(blank=True, verbose_name='SNMPv3 Auth Password'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmpv3_auth_protocol',
            field=models.CharField(blank=True, choices=[('', 'None'), ('md5', 'MD5'), ('sha', 'SHA')], default='', max_length=20, verbose_name='SNMPv3 Auth Protocol'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmpv3_priv_password',
            field=apps.devices.fields.EncryptedCharField(blank=True, verbose_name='SNMPv3 Privacy Password'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmpv3_priv_protocol',
            field=models.CharField(blank=True, choices=[('', 'None'), ('des', 'DES'), ('aes', 'AES')], default='', max_length=20, verbose_name='SNMPv3 Privacy Protocol'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmpv3_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='SNMPv3 Username'),
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_version',
            field=models.CharField(choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=5),
        ),
    ]
