# Generated by Django 5.2 on 2026-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_add_wlan_device_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='access_vlan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Access VLAN (PVID)'),
        ),
    ]
