# Generated by Django 5.2 on 2026-06-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_create_monitor_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_ok_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần poll OK gần nhất'),
        ),
    ]
