# Generated by Django 5.2 on 2026-07-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_topologylink_switch_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('huawei', 'Huawei'), ('mikrotik', 'MikroTik'), ('fortinet', 'Fortinet'), ('synology', 'Synology'), ('microsoft', 'Microsoft')], max_length=50, verbose_name='Hãng'),
        ),
    ]
