# Generated by Django 5.2 on 2026-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_device_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('huawei', 'Huawei'), ('synology', 'Synology'), ('microsoft', 'Microsoft')], max_length=50, verbose_name='Hãng'),
        ),
    ]
