# Generated by Django 6.0.6 on 2026-09-28 04:55

import apps.devices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_device_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ilo_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP iLO'),
        ),
        migrations.AddField(
            model_name='device',
            name='ilo_password',
            field=apps.devices.fields.EncryptedCharField(blank=True, verbose_name='iLO Password'),
        ),
        migrations.AddField(
            model_name='device',
            name='ilo_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='iLO Username'),
        ),
    ]
