# Generated by Django 5.2.16 on 2026-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_device_ilo_ip_address_device_ilo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ilo_last_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='ilo_last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
