# Generated by Django 5.2.16 on 2026-10-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_device_ilo_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ilo_cert_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='iLO cert SHA-256'),
        ),
    ]
